<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>WpfImageProcessing</RootNamespace>
    <AssemblyName>ImageProgram</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AtiWpf.Ui" Version="1.0.52" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resource\TestImages\" />
  </ItemGroup>

</Project>
